// Code generated by mockery v1.0.0. DO NOT EDIT.

package encoderesponse

import mock "github.com/stretchr/testify/mock"

// MockEncodeResponse is an autogenerated mock type for the EncodeResponse type
type MockEncodeResponse struct {
	mock.Mock
}

// Encode provides a mock function with given fields: v
func (_m *MockEncodeResponse) Encode(v interface{}) error {
	ret := _m.Called(v)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(v)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
